#################################################################################
#                               OneBranch Pipelines                             #
# Pack and Sign DataFactory.MCP NuGet Packages                                  #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - DataFactory.MCP/*

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - DataFactory.MCP/*

parameters:
  - name: "debug"
    displayName: "Enable debug output"
    type: boolean
    default: false

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task
  system.debug: ${{ parameters.debug }}
  ENABLE_PRS_DELAYSIGN: 1
  BuildConfiguration: "Release"
  DataFactorySourceDir: ""
  REPOROOT: $(Build.SourcesDirectory)
  OUTPUTROOT: $(REPOROOT)\out
  WindowsContainerImage: "onebranch.azurecr.io/windows/ltsc2022/vse2022:latest"

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    featureFlags:
      WindowsHostVersion: "1ESWindows2022"

    globalSdl:
      tsa:
        enabled: true
      credscan:
        enabled: true
      policheck:
        enabled: true
        break: false
      armory:
        enabled: true
        break: true
      binskim:
        enabled: true
        break: true

    stages:
      - stage: build
        jobs:
          - job: main
            pool:
              type: windows

            variables:
              ob_outputDirectory: '$(REPOROOT)\out'
              ob_sdl_binskim_break: true
              ob_symbolsPublishing_enabled: true
              ob_nugetPublishing_enabled: true
              # Force NuGet to use only our config
              NUGET_PACKAGES: '$(Agent.TempDirectory)\.nuget\packages'
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
              DOTNET_CLI_TELEMETRY_OPTOUT: "true"

            steps:
              # Setup .NET
              - task: UseDotNet@2
                displayName: "Install .NET SDK"
                inputs:
                  packageType: "sdk"
                  version: "10.0.x"
                  includePreviewVersions: true

              # Restore packages using MSBuild (exactly like OneBranch.Official.yml)
              - task: MSBuild@1
                displayName: "Restore packages"
                inputs:
                  solution: '$(Build.SourcesDirectory)\DataFactory.MCP\DataFactory.MCP.csproj'
                  msbuildLocationMethod: "version"
                  msbuildVersion: "latest"
                  platform: "Any CPU"
                  configuration: "$(BuildConfiguration)"
                  msbuildArguments: '/t:Restore /p:RestoreConfigFile=$(Build.SourcesDirectory)\nuget.config'
                  clean: true
                  maximumCpuCount: true
                  logProjectEvents: true

              # Build the project using MSBuild
              - task: MSBuild@1
                displayName: "Build project"
                inputs:
                  solution: '$(Build.SourcesDirectory)\DataFactory.MCP\DataFactory.MCP.csproj'
                  msbuildLocationMethod: "version"
                  msbuildVersion: "latest"
                  platform: "Any CPU"
                  configuration: "$(BuildConfiguration)"
                  msbuildArguments: "/v:n /nr:false /p:build_all_project_references=0"
                  clean: false
                  maximumCpuCount: true
                  logProjectEvents: true

              # Sign binary files with OneBranch (exactly like OneBranch.Official.yml)
              - task: onebranch.pipeline.signing@1
                displayName: "Sign binary files"
                inputs:
                  command: "sign"
                  signing_profile: "external_distribution"
                  files_to_sign: |
                    **/*.exe;
                    **/*.dll;
                    **/*.ps1;
                    **/*.psm1;
                    **/*.psd1;
                  search_root: '$(Build.SourcesDirectory)\DataFactory.MCP'

              # Pack the project using MSBuild (like OneBranch.Official.yml)
              - task: MSBuild@1
                displayName: "Build NuGet Packages"
                inputs:
                  solution: '$(Build.SourcesDirectory)\DataFactory.MCP\DataFactory.MCP.csproj'
                  msbuildLocationMethod: "version"
                  msbuildVersion: "latest"
                  platform: "Any CPU"
                  configuration: "$(BuildConfiguration)"
                  msbuildArguments: "/t:Pack /v:n /nr:false /p:build_all_project_references=0"
                  clean: false
                  maximumCpuCount: true
                  logProjectEvents: true

              # Sign NuGet packages with OneBranch (exactly like OneBranch.Official.yml)
              - task: onebranch.pipeline.signing@1
                displayName: "Sign NuGet Packages"
                inputs:
                  command: "sign"
                  signing_profile: "external_distribution"
                  files_to_sign: "*.nupkg;"
                  search_root: '$(Build.SourcesDirectory)\DataFactory.MCP\bin\$(BuildConfiguration)'

              # Verify packages are signed
              - task: CmdLine@2
                displayName: "Verify packages are signed"
                inputs:
                  script: "dotnet nuget verify $(OUTPUTROOT)\\*.nupkg"
                continueOnError: true

              # List created packages for verification
              - task: CmdLine@2
                displayName: "List created packages"
                inputs:
                  script: 'dir "$(OUTPUTROOT)" *.nupkg /s'
                continueOnError: true
